[colors.primary]
background = "#0A0716"
foreground = "#f5eafd"

[colors.cursor]
text = "#0A0716"
cursor = "#f5eafd"

[colors.vi_mode_cursor]
text = "#0A0716"
cursor = "#f5eafd"

[colors.search.matches]
foreground = "#0A0716"
background = "#f5eafd"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#8c53b7"
background = "#f5eafd"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0A0716"
red = "#A70B68"
green = "#7f049e"
yellow = "#790aac"
blue = "#ca2cb0"
magenta = "#a604e9"
cyan = "#C429B2"
white = "#c78bf5"

[colors.bright]
black = "#8c53b7"
red = "#f1279f"
green = "#c911f8"
yellow = "#b52af3"
blue = "#e37bd1"
magenta = "#cc58fc"
cyan = "#ef6469"
white = "#f5eafd"

[colors.dim]
black = "#f5eafd"
red = "#f1279f"
green = "#c911f8"
yellow = "#b52af3"
blue = "#e37bd1"
magenta = "#cc58fc"
cyan = "#ef6469"
white = "#8c53b7"
